DELETE http://localhost:3003/api/blogs/624449b9131143ce9fd247db
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZsZWtpY2ExMiIsImlkIjoiNjI0NDQ5OTcxMzExNDNjZTlmZDI0N2Q3IiwiaWF0IjoxNjQ4NjQyNDY3LCJleHAiOjE2NDg2NDYwNjd9.7nhc8nd29itMHwrXqYvRiaOkT0Sw4xkgrBH6vKPr8PY
